els-ASAP auto commit file/tag srptools-0.0.4-15.el6.src.rpm

diff --git a/srptools.init b/srptools.init
--- a/srptools.init
+++ b/srptools.init
@@ -9,7 +9,10 @@
 ### BEGIN INIT INFO
 # Provides:       srpd
 # Default-Stop: 0 1 2 3 4 5 6
-# Required-Stop:
+# Required-Start: rdma
+# Required-Stop: rdma
+# Should-Start: $network NetworkManager opensm
+# Should-Stop: $network MetworkManager opensm
 # Short-Description: Starts and stops the InfiniBand SRP client service
 # Description: The InfiniBand SRP client service attaches to SRP devices
 #	on the InfiniBand fabric and makes them appear as local disks to
@@ -28,7 +31,7 @@ prog=/usr/sbin/srp_daemon.sh
 
 SRP_LOADED=no
 if [ -f $RDMA_CONFIG ]; then
-    . $CONFIG
+    . $RDMA_CONFIG
     if [ "${SRP_LOAD}" == "yes" ]; then
 	SRP_LOADED=yes
     fi
@@ -37,14 +40,17 @@ fi
 start()
 {
     if [ "$SRP_LOADED" == "no" ]; then
+    	echo "SRP kernel services not configured, unable to start SRP daemon"
 	return 6
     fi
 
     echo -n "Starting SRP daemon service:"
 
-    daemon $prog
+    daemon $prog >/dev/null 2>&1 &
+    sleep 1
+    checkpid `cat $pidfile`
     RC=$?
-    [ $RC -eq 0 ] && touch $subsys
+    [ $RC -eq 0 ] && (touch $subsys; echo_success) || echo_failure
     echo
     return $RC
 }
